### ISSUE TITLE
WWW-Authenticate header is not parsed properly

### ISSUE THREAD

**Issue by andreyvolosyuk** [aler9/gortsplib#1]
Parser can not parse a header with merely comma separators rather than comma+space and parameters with empty values within double quotes.

>  Digest realm="Please log in with a valid username",nonce="752a62306daf32b401a41004555c7663",opaque="",stale=FALSE,algorithm=MD5

No luck for the example :(

**Comment by aler9** [comment]
Hello, the library has evolved a lot since may, the string you posted is now fully supported and has also been added to the test suite.
