### ISSUE TITLE
Connection data (c=) field is missing from SDP generated by Track.write()

### ISSUE THREAD

**Issue by nu774** [aler9/gortsplib#10]
rfc4566 says (5.7. Connection Data ("c=")):
>A session description MUST contain either at least one "c=" field in each media description or a single "c=" field at the session level.

rfc2326 says (C.1.7. Connection Information):
>    In SDP, the "c=" field contains the destination address for the media stream. However, for on-demand unicast streams and some multicast streams, the destination address is specified by the client via the SETUP request. Unless the media content has a fixed destination address, the "c=" field is to be set to a suitable null value. For addresses of type "IP4", this value is "0.0.0.0".

So I think it's required at least on the session global level, and it can be just like this:
"c=IN IP4 0.0.0.0"

Apple's Darwin Streaming Server actually requires this.
It accepts SDP without c= line on ANNOUNCE, but returns 404 on succeeding SETUP request.

**Comment by aler9** [comment]
Hello, thanks for reporting the bug, the line "c=IN IP4 0.0.0.0" is now sent when calling tracks.Write()
