### ISSUE TITLE
Suggesting decrease of rtpPayloadMaxSize to 1200

### ISSUE THREAD

**Issue by flo-eyeson-team** [aler9/gortsplib#106]
The rtpPayloadMaxSize (https://github.com/aler9/gortsplib/blob/main/pkg/rtph264/encoder.go#L13) is fixed to 1460, which is too large to fit a broader range of network configurations, resulting in fragmentations on the IP-layer or a complete packet drop in certain settings. Pion e.g. uses 1200 (https://github.com/pion/webrtc/blob/v3.1.24/constants.go#L27) for outbound RTP packets.

**Comment by aler9** [comment]
Hello, can you provide a reference? that parameter can be certainly lowered, but it influences only RTP streams that are generated from the library, that are a small minority.

most streams that are pulled from cameras have a MTU of ~1450 bytes,  and so do all streams generated with ffmpeg and GStreamer.

**Comment by flo-eyeson-team** [comment]
Using gortsplib for forwarding an rtmp-client to a webrtc-server (https://github.com/eyeson-team/ghost/tree/main/examples/rtmp-server) without any transcoding. Making rtpPayloadMaxSize configurable would be fine too.

**Comment by aler9** [comment]
A parameter `PayloadMaxSize` has been added to `rtpaac.Encoder` and `rtph264.Encoder`. Initialization has been simplified in order to make most fields optional.

**Comment by aler9** [comment]
BTW i've discovered why pion MTU is 1200... because they use SRTP which has an extra layer.
