### ISSUE TITLE
Why not return an error?

### ISSUE THREAD

**Issue by vahid-sohrabloo** [aler9/gortsplib#11]
why this line does not return an error? is that a bug?
https://github.com/aler9/gortsplib/blob/9ecbb6be67f1b3fc3e89025651c9f53ba080d1c2/connclient.go#L482

**Comment by aler9** [comment]
Hello, that was obviously a bug, thanks for reporting it :)

**Comment by vahid-sohrabloo** [comment]
We have the same bug  on these lines
 https://github.com/aler9/gortsplib/blob/38f93a1a7e13a76ba7b7c151f2ba18162663abd5/connclient.go#L600
 https://github.com/aler9/gortsplib/blob/38f93a1a7e13a76ba7b7c151f2ba18162663abd5/connclient.go#L658
