### ISSUE TITLE
Pass RTP packet to pion/webrtc NewTrackLocalStaticRTP

### ISSUE THREAD

**Issue by Coimbra1984** [aler9/gortsplib#110]
Hi,

I used you sample code [client-read-h264](https://github.com/aler9/gortsplib/tree/main/examples/client-read-h264). I want to send the H264 stream to a pion/webrtc PeerConnection. Therefore I created a new Pion stream:
`rtpTrack, errTrack := webrtc.NewTrackLocalStaticRTP(webrtc.RTPCodecCapability{MimeType: webrtc.MimeTypeH264}, "video", "pion")`
The pion stream has a function rtpTrack.WriteRTP(p *rtp.Packet), but they include the following package:
`"github.com/pion/rtp"`
On the other hand I have your client:
`c := gortsplib.Client{}` with a 
`c.OnPacketRTP = func(trackID int, pkt *rpt.Packet) {...}` signature, but you include 
`"github.com/pion/rtp/v2"`
This means I cannot pass directly your packets to the PeerConnection track because of this mismatch. Do you have an idea on how to convert from one world into the other. As far as I see the struct definitions are exactly the same...

Thanks

**Comment by Meonardo** [comment]
@Coimbra1984 I have the same issue when I used the latest version of `gortsplib`, the urgly way to make this repo and `pion/webrtc` work together is downgrade this to `github.com/aler9/gortsplib v0.0.0-20220303160144-a541ae8f963c`.

**Comment by aler9** [comment]
hello, due to popular demand, pion/rtp was downgraded to v1. This restores integration with pion/webrtc.
