### ISSUE TITLE
Option to disable automatic RTCP Sender Report 

### ISSUE THREAD

**Issue by eipporko** [aler9/gortsplib#111]
I wanted to use gortsplib to redirect the RTP and RTCP traffic generated by an external application towards RTSP-Simple-Server. But seems that gortsplib is sending his own RTCP packages :(

Because synchronization with others streams I require to send the RTCP packets without modify the NTP value.

Is there any way to disable the automatic Sender Reports generated when publishing?

**Comment by aler9** [comment]
Option `DisableRTCPSenderReports` has been added to both client and server.
