### ISSUE TITLE
Example build errors

### ISSUE THREAD

**Issue by gmonk** [aler9/gortsplib#113]
Receive the following when trying to build any of the examples
pkg/mod/github.com/aler9/gortsplib@v0.0.0-20220324142719-7d9c882cc95b/client.go:769:11: pkt.PaddingSize undefined (type *rtp.Packet has no field or method PaddingSize)

**Comment by aler9** [comment]
hello, due to popular demand, pion/rtp was downgraded to v1. This fixes build errors.
