### ISSUE TITLE
"client-read-republish" example fails in case when Control URL Attribute is expressed as relative URL

### ISSUE THREAD

**Issue by ritj** [aler9/gortsplib#120]
When using the "client-read-republish" example to publish the stream to the server, deployed using example "server".

Setup:
Camera <=> Relay Unit(client-read-republish) <=> RTSP Server (server)

The stream works fine with another Camera when the tracks are:
`v=0
o=- 0 0 IN IP4 127.0.0.1
s=Stream
c=IN IP4 0.0.0.0
t=0 0
m=video 0 RTP/AVP 35
a=rtpmap:35 H264/90000
a=fmtp:35 packetization-mode=1; sprop-parameter-sets=
a=control:video`

But the same fails (400: Bad Request) with Camera sending the Control URL Attribute(a=control), as relative URL:
`tracks: v=0
o=- 0 0 IN IP4 127.0.0.1
s=Stream
c=IN IP4 0.0.0.0
t=0 0
m=video 0 RTP/AVP 35
a=rtpmap:35 H264/90000
a=fmtp:35 packetization-mode=1; sprop-parameter-sets=
a=control:rtsp://192.168.0.218/?rtsp_tunnel&stream=video`

**Comment by aler9** [comment]
Hello, thanks for reporting this issue, basically what happens is the following:

1. tracks are read from the camera
2. during `StartPublishing()`, their control attribute is overridden
3. during `SetupAndPlay()`, tracks can't be set up since their control attribute is now wrong
