### ISSUE TITLE
rtp vp8&vp9 video steam decode  support in future ?

### ISSUE THREAD

**Issue by Bmixo** [aler9/gortsplib#127]
rtp vp8&vp9 video steam decode  support in future ?

**Comment by Bmixo** [comment]
in order to replace gstreamer vp8 decode pipe

https://github.com/pion/example-webrtc-applications/tree/master/gstreamer-receive

buf := make([]byte, 1400)
for {
	i, _, readErr := track.Read(buf)
	if readErr != nil {
		panic(err)
	}

	pipeline.Push(buf[:i])
}

**Comment by aler9** [comment]
Hello, of course they will be added, but in the meanwhile you can use pion/rtp's decoders, here:

https://github.com/pion/rtp/blob/master/codecs/vp8_packet.go

They're slightly different and less efficient than the ones provided here (and that's the reason why i don't use them) but VP8, VP9 and H265 are fully supported.

**Comment by aler9** [comment]
VP8 encoder and decoder has been added with #149
