### ISSUE TITLE
Store prefix with NALU buffer

### ISSUE THREAD

**Issue by bmharper** [aler9/gortsplib#131]
Firstly, thanks for an awesome library. It's been a joy to use so far.

I just have one idea I'd like to put out there:

In my own code, I use a `NALU` struct
```go
type NALU struct {
	PrefixLen int // If zero, then no prefix. If 3 or 4, then 00 00 01 or 00 00 00 01.
	Payload   []byte
}
```
This reduces the number of times that one needs to make a copy of the NALU simply to add the 3 header bytes, or to remove them, etc. For example, when I receive an RBSP NALU from a camera, I have to copy the buffer anyway, so then I add the 3 prefix bytes right there. Then, when I want to send that NALU to avcodec, I don't need to make a copy of the buffer again, purely for the sake of adding those 3 prefix bytes. I'm targeting a Raspberry Pi 4, which has only 4GB/s of memory bandwidth, so the memory copies add up. If I want to access the buffer *without* the prefix, then I can simply use `nalu.Payload[nalu.PrefixLen:]`

I just wanted to share the idea in case it's useful... Feel free to close this issue immediately.

**Comment by aler9** [comment]
Hello, the main aim of library is dealing with RTSP/RTP streams. In RTP, H264 NALUs are not encoded without the 0x000001 prefix (the prefix-based encoding is called Annex-B), therefore adding it would decrease performance, as all NALUs should be copied into an additional buffer.

Anyway, the libav code i added into the example file is only an example, there's probably a way to pass NALUs to libav without the prefix.
