### ISSUE TITLE
Limited UDP port count

### ISSUE THREAD

**Issue by T1mbo** [aler9/gortsplib#179]
Hi! Thank you for this project!
Now I am writing a simple client for Linux that requests a RTSP stream from the single camera, parses it into raw frames and writes it to disk. 

Right now I can't continue my project because I'm faced with a strange problem in the form of file descriptor restrictions. To process each camera I create a separate instance of an application.

And when I try to run > 248 instances, I get a strange limit of 1024 FD's, which causes a lot of CPU load because the client is trying to find a free port. 

netstat:
![изображение](https://user-images.githubusercontent.com/892264/214159255-900ecce2-557c-49c9-bcf4-9a33c09777c0.png)

strace: 
![изображение](https://user-images.githubusercontent.com/892264/214159375-5cad6df7-0bf1-46f0-8ac5-20c297f611cc.png)

I checked all the limits I could: ulimit, sysctl, systemd and everywhere the maximum number of open files is set above 1024:

ulimit:
![изображение](https://user-images.githubusercontent.com/892264/214159941-20bb6073-5aa2-4a9b-a133-4a2f337d8673.png)

sysctl:
![изображение](https://user-images.githubusercontent.com/892264/214160171-efe0b6bd-becd-46ef-ad2d-cf0741a64a1b.png)

systemd:
![изображение](https://user-images.githubusercontent.com/892264/214160525-639d7ec1-12e9-4cae-bfa0-3876b0d0d522.png)

 When searching for problems with file descriptors, I tried to capture the stream using ffmpeg and I did not find this problem there, nor did I find any restrictions when simply opening UDP sockets using Python. 

ffmpeg:
![изображение](https://user-images.githubusercontent.com/892264/214160945-1a723c2a-5071-4c14-8342-4fa339056430.png)

To confirm the problem, I ran examples/client-read and got exactly the same problem.
This problem is independent of the OS. For example, I reproduced the problem on Debian and Fedora. 

Tell me what could be the problem?

**Comment by aler9** [comment]
Hello, i checked the client code and i found a bug:

https://github.com/aler9/gortsplib/blob/1d915dcc81766ec9df9032571335ffd105999804/client_udpl.go#L49

this line is intended to return a even port in range 65535-10000, but since `randIntn` is

https://github.com/aler9/gortsplib/blob/1d915dcc81766ec9df9032571335ffd105999804/client_udpl.go#L20

```
randIntn(65535-10000)/2) = randIntn(27767) = rand() & (27767-1) = rand() & 110110001110110
```

The function returns only 2^10 possible values, therefore 1024 values.

I will fix it ASAP.

**Comment by aler9** [comment]
This has been fixed and a new version has been released.

**Comment by aler9** [comment]
added in v0.21.3
