### ISSUE TITLE
unable to find control attribute

### ISSUE THREAD

**Issue by photostorm** [aler9/gortsplib#20]
URL: rtsp://127.0.0.1:554/trackID=0

These seems to be a bug in the BasePathControlAttr() method. Preventing VLC from working.

https://github.com/aler9/gortsplib/blob/master/pkg/base/url.go#L112

**Comment by aler9** [comment]
Hello, the problem of that specific URL is that it doesn't contain a path, like

```
rtsp://127.0.0.1:554/path/trackID=0
```

Why do you need to support URLs without paths? is there a camera or server that requires them?

**Comment by photostorm** [comment]
I do not need. I just noticed my rtsp server stopped working and that was the format of my URL.

**Comment by aler9** [comment]
VLC uses that path if it can't connect to the original one; for instance, if the original path is

```
rtsp://127.0.0.1:554/testing
```

and the server replies with a status code != 200, then VLC retries with

```
rtsp://127.0.0.1:554/
```

But at the moment i can't see any practical use in supporting the latter.
