### ISSUE TITLE
session vs connection state

### ISSUE THREAD

**Issue by alokpr** [aler9/gortsplib#23]
According to RTSP [specification](https://tools.ietf.org/html/rfc2326), there is no notion of "connection" state. There is only the notion of "session" state.

However gortsplib attaches state to connections: https://github.com/aler9/gortsplib/blob/557fadcd3cf7935a4a2422933161b2b3fdafc00f/serverconn.go#L127

Relevant text from the spec:

[Section 1.1](https://tools.ietf.org/html/rfc2326#section-1.1)
> There is no notion of an RTSP connection; instead, a server maintains a session labeled by an identifier. An RTSP session is in no way tied to a transport-level connection such as a TCP connection. During an RTSP session, an RTSP client may open and close many reliable transport connections to the server to issue RTSP requests. Alternatively, it may use a connectionless transport protocol such as UDP.

[Section 1.7](https://tools.ietf.org/html/rfc2326#section-1.7)
> RTSP controls a stream which may be sent via a separate protocol, independent of the control channel. For example, RTSP control may occur on a TCP connection while the data flows via UDP. Thus, data delivery continues even if no RTSP requests are received by the media server. Also, during its lifetime, a single media stream may be controlled by RTSP requests issued sequentially on different TCP connections. Therefore, the server needs to maintain "session state" to be able to correlate RTSP requests with a stream.

[Section 12.37](https://tools.ietf.org/html/rfc2326#section-12.37)
> Note that a session identifier identifies a RTSP session across transport sessions or connections. Control messages for more than one RTSP URL may be sent within a single RTSP session. Hence, it is possible that clients use the same session for controlling many streams constituting a presentation, as long as all the streams come from the same server. However, multiple "user" sessions for the same URL from the same client MUST use different session identifiers. The session identifier is needed to distinguish several delivery requests for the same URL coming from the same client.

**Comment by aler9** [comment]
Yes, this would be a good enhancement, but in my opinion connection state must be tracked anyhow, and session must be teared down after a timeout.

**Comment by aler9** [comment]
Sessions have been implemented in 2590436 and state is now associated to sessions and not to clients
:v: :v: :v: :v: :v:

**Comment by alokpr** [comment]
Awesome!
