### ISSUE TITLE
Server examples, updating readers map after closing connection

### ISSUE THREAD

**Issue by mateusz28** [aler9/gortsplib#26]
Hi, I've found a small issue in server examples. When the reader closes connections handler to connection is not removed from the reader's map. It makes unnecessary onFrame for loop iteration or RTP frame repetition on reader site. The way I handle it is fairly simple:
```	
if conn == publisher {
		publisher = nil
		sdp = nil
	} else {
		delete(readers, conn)
	}
```
I'm quite new to go so I'm not sure if it is the clean and correct way of handling map element removal. Please consider fixing both server and server-udp examples the same or similar way.

**Comment by aler9** [comment]
Hello, thank you very much for reporting this, it has been fixed.
