### ISSUE TITLE
Unable to go get the module

### ISSUE THREAD

**Issue by notkeddad** [aler9/gortsplib#28]
For some reason, I can't `go get` this project:
```
[keddad@priest mgm]$ go get github.com/aler9/gortsplib
go get: github.com/aler9/gortsplib@none updating to
        github.com/aler9/gortsplib@v0.0.0-20210316211856-c2de28c18558 requires
        github.com/notedit/rtmp@v0.0.0: reading github.com/notedit/rtmp/go.mod at revision v0.0.0: unknown revision v0.0.0
```
Other modules are getting installed just fine. I don't really write Go code that much, but I guess it might be some kind of project issue? Can anybody reproduce this?

**Comment by aler9** [comment]
Hello, thanks for reporting the issue, it has been fixed. Since it could take some time before the Go proxy system gets updated, download the library with

```
GOPROXY=direct go get github.com/aler9/gortsplib
```
