### ISSUE TITLE
Decode unconventionally sorted transport header

### ISSUE THREAD

**Issue by napieralla** [aler9/gortsplib#34]
Some RTSP-servers deliver unconventionally sorted transport header fields. Such as a camera that I'm trying to connect to whose tranport header can look like this:

`Transport: RTP/AVP;ssrc=22345755;unicast;client_port=14186-14187;server_port=49152-49153`

These headers cannot be parsed at the moment because the library expects the `unicast | multicast` parameter to always come in second place, after the stream protocol and before the other parameters.

Would you consider supporting these kind of transport headers, where parameters (after the stream protocol) might be listed in unconventional order, **or allowing a PR doing this**?

Currently an error is thrown [here](https://github.com/aler9/gortsplib/blob/178fe919ea26e72ba5f6121f7f594d2197652ed1/pkg/headers/keyval.go#L11) as no `=`-sign is found before the separator or end-of-string. That function could be rewritten to support keys without value (`append` is another possible value-less parameter-key), and [this](https://github.com/aler9/gortsplib/blob/c1cd32257f377fdeb7b49c88c58b9a1fc4ca7d2e/pkg/headers/transport.go#L123) function would have to be rewritten to not expect `unicast | multicast` after the first `;`.

**Comment by aler9** [comment]
> Would you consider supporting these kind of transport headers, where parameters (after the stream protocol) might be listed in unconventional order, or allowing a PR doing this?

Yes, since RTSP is implemented in a very "creative" way in a lot of cameras, the library must also support most edge cases. Send a PR and it will be merged :)

**Comment by aler9** [comment]
fixed by #38
