### ISSUE TITLE
Incorrect checks for ErrServerTransportWrongInterleavedIDs

### ISSUE THREAD

**Issue by RogerHardiman** [aler9/gortsplib#47]
Over on simple-rtsp-server I had an issue with a RTSP client from IndigoVision(Motorol) not connecting

The issue comes down to these checks
```
                        if inTH.InterleavedIDs[0] != (trackID*2) ||
                                inTH.InterleavedIDs[1] != (1+trackID*2) {
                                return &base.Response{
                                                StatusCode: base.StatusBadRequest,
                                        }, liberrors.ErrServerTransportHeaderWrongInterleavedIDs{
                                                Expected: [2]int{(trackID * 2), (1 + trackID*2)}, Value: *inTH.InterleavedIDs,
                                        }
                        }
                }
```

The Interleaved values in the RTP SETUP command are not related to the Track ID. They are just two numbers that the RTSP client can pick freely. (I confirmed with the RFC)

So these two SETUP commands (which are valid) will fail with your library.

SETUP rtsp://127.0.0.1:8554/transcode/trackID=0 RTSP/1.0
**Transport: RTP/AVP/TCP;unicast;interleaved=168-169**   <---- note the interleaved value is not related to Track 0
User-Agent: IndigoVision RTSP client
CSeq: 2

RTSP/1.0 400 Bad Request
CSeq: 2
Server: gortsplib

SETUP rtsp://127.0.0.1:8554/transcode/trackID=1 RTSP/1.0
**Transport: RTP/AVP/TCP;unicast;interleaved=170-171**  <--- and the SETUP for trackID 1 has its own interleaved values
User-Agent: IndigoVision RTSP client
CSeq: 3

I've worked on the SharpRTSP c# open source library and the Yellowstone RTSP library (JS + NodeJS runtime) and have had to cater for this part of the RFC myself.

Never read any Go before, seems easy to follow but not tried to build and run under an IDE to try and fix and a PR

**Comment by aler9** [comment]
now it's possible to setup tracks with arbitrary interleaved IDs.
