### ISSUE TITLE
DialPublish: Error on SETUP request when tracks passed by the caller already contain "a:control" attribute

### ISSUE THREAD

**Issue by nu774** [aler9/gortsplib#48]
doAnnounce() *appends* "a:control" attribute to the each track passed by the caller.
In doSetup(), we get track URL by Track.URL() and it picks up *first* occurence of a:control of the track.
On the other hand, SDP written by Tracks.Write() will always put "a:control trackID=n"

As a result, when tracks passed to doAnnounce() already contain "a:control", SDP and SETUP URL will not match, and the server responds with error.

**Comment by aler9** [comment]
Hello, thanks for reporting this issue, now clients are able to publish tracks with pre-existing control attributes.
