### ISSUE TITLE
ReadTransport() is incompatible with ffmpeg listen mode

### ISSUE THREAD

**Issue by nu774** [aler9/gortsplib#5]
ReadTransport() accepts only mode=PLAY or mode=RECORD (which seems to agree with rfc2326)
On the other hands, ffmpeg seems to have been sending "mode=receive" since 8 years ago or so from this commit:
https://gitlab.websupport.sk/peter.kovar/ffmpeg-mvc/commit/a8ad6ffafe89e3a83f343f69249338e8245816f7?expanded=1
(look at rtsp_read_setup() in rtspdec.c)

This may be an issue on ffmpeg side, but as a result, DialPublish() fails against ffmpeg RTSP listen mode.

**Comment by nu774** [comment]
Apple's Darwin Streaming Server also allows either mode=receive or mode=record for recording.
Maybe historical reason?

https://github.com/macosforge/dss/blob/master/Server.tproj/RTSPRequest.cpp#L694

**Comment by aler9** [comment]
Hello, thanks for reporting the issue, the `receive` mode is now fully supported.
