### ISSUE TITLE
VLC pull streaming error

### ISSUE THREAD

**Issue by dongjialong2006** [aler9/gortsplib#54]
pull streaming about 2-3 hours, vlc shut down
report keep-alive received 400 bad request

**Comment by dongjialong2006** [comment]
VLC UDP

**Comment by dongjialong2006** [comment]
VLC  RTP/UDP

**Comment by aler9** [comment]
Please provide
1) the code you're using
2) full VLC log, that can be generated by launching VLC with the `-vvv` flag

**Comment by dongjialong2006** [comment]
main debug: picture might be displayed late (missing 2 ms)
main debug: picture might be displayed late (missing 7 ms)
main debug: picture might be displayed late (missing 8 ms)
main debug: picture might be displayed late (missing 13 ms)
main debug: picture might be displayed late (missing 12 ms)
main debug: picture might be displayed late (missing 4 ms)
main debug: picture might be displayed late (missing 8 ms)
main debug: picture might be displayed late (missing 3 ms)
main debug: picture might be displayed late (missing 4 ms)
main warning: picture is too late to be displayed (missing 34 ms)
main debug: picture might be displayed late (missing 13 ms)
main debug: picture might be displayed late (missing 18 ms)
main debug: picture might be displayed late (missing 8 ms)
main debug: picture might be displayed late (missing 8 ms)
main warning: picture is too late to be displayed (missing 38 ms)
main warning: picture is too late to be displayed (missing 30 ms)
main debug: picture might be displayed late (missing 5 ms)
main debug: picture might be displayed late (missing 0 ms)
main debug: picture might be displayed late (missing 13 ms)
main debug: picture might be displayed late (missing 8 ms)
main debug: picture might be displayed late (missing 14 ms)
main debug: picture might be displayed late (missing 12 ms)
main debug: picture might be displayed late (missing 15 ms)
main warning: picture is too late to be displayed (missing 36 ms)
main debug: picture might be displayed late (missing 1 ms)
main debug: picture might be displayed late (missing 11 ms)
main warning: picture is too late to be displayed (missing 21 ms)
main debug: picture might be displayed late (missing 0 ms)
main debug: picture might be displayed late (missing 16 ms)
main warning: picture is too late to be displayed (missing 61 ms)
main warning: picture is too late to be displayed (missing 21 ms)
main debug: picture might be displayed late (missing 1 ms)
main debug: picture might be displayed late (missing 6 ms)
main debug: picture might be displayed late (missing 4 ms)
main warning: picture is too late to be displayed (missing 36 ms)
main warning: picture is too late to be displayed (missing 21 ms)
main debug: picture might be displayed late (missing 0 ms)
live555 error: keep-alive failed: 400 Bad Request
main debug: EOF reached
main debug: waiting decoder fifos to empty
main debug: waiting decoder fifos to empty
main debug: waiting decoder fifos to empty
main debug: waiting decoder fifos to empty
main debug: waiting decoder fifos to empty
main debug: waiting decoder fifos to empty
main debug: waiting decoder fifos to empty
main debug: waiting decoder fifos to empty
main debug: waiting decoder fifos to empty
main debug: waiting decoder fifos to empty
main debug: waiting decoder fifos to empty
main debug: waiting decoder fifos to empty
main debug: killing decoder fourcc `h264'
main debug: removing module "avcodec"
main debug: saving a free vout
main debug: reusing provided vout
main debug: removing module "h264"
main debug: removing module "live555"
main debug: Program doesn't contain anymore ES
main debug: dead input
main debug: changing item without a request (current 0/1)
main debug: nothing to play
main debug: destroying useless vout
main debug: removing module "direct3d11"
direct3d11 debug: Direct3D11 resources destroyed
qt debug: IM: Deleting the input
direct3d11 debug: Direct3D11 device adapter closed
direct3d11 error: SetThumbNailClip failed: 0x800706f4
direct3d11 debug: Win32 Vout EventThread terminating
direct3d11 debug: Win32VoutCloseWindow
direct3d11 debug: WinProc WM_DESTROY
main debug: removing module "inhibit"
qt debug: releasing video...
qt debug: Video is not needed anymore
qt warning: orphaned video window
main debug: removing module "freetype"
main debug: removing module "yuvp"
main debug: removing module "swscale"

**Comment by aler9** [comment]
You need to post the Golang code you used to replicate the issue.

**Comment by dongjialong2006** [comment]
I had traced the cause of the trouble, It's my business logic，Sorry

**Comment by dongjialong2006** [comment]
In "OnPlay" Method
