### ISSUE TITLE
ERR: unable to get clock rate of track 0: invalid format ([98 96])

### ISSUE THREAD

**Issue by Ricky-Yeh** [aler9/gortsplib#65]
I had an IP cam, and I cannot connect to it with rtsp-simple-server.
Its SDP contains a video media with two payload types.
> m=video 0 RTP/AVP 98 96

I found that gortsplib would only accept one media type in each payload ([track.go](https://github.com/aler9/gortsplib/blob/main/track.go#L79))
But in RFC4566 SDP [Media Descriptions](https://datatracker.ietf.org/doc/html/rfc4566#section-5.14) section,
It said that:
> If the <proto> sub-field is "RTP/AVP" or "RTP/SAVP" the <fmt>
> sub-fields contain RTP payload type numbers.  When a list of
> payload type numbers is given, this implies that all of these
> payload formats MAY be used in the session, but the first of these
> formats SHOULD be used as the default format for the session.
 

The detail error message is in below:
----
2021/07/22 11:27:48 I [0/0] rtsp-simple-server v0.0.0
2021/07/22 11:27:48 I [0/0] [RTSP] TCP listener opened on :8554
2021/07/22 11:28:12 I [0/0] [path video/abc] [rtsp source] started
2021/07/22 11:28:12 D [0/0] [path video/abc] [rtsp source] connecting
2021/07/22 11:28:12 D [0/0] [path video/abc] [rtsp source] c->s OPTIONS rtsp://172.16.0.33:3456/Media/Normal?streamindex=1 RTSP/1.0
CSeq: 1
User-Agent: gortsplib

2021/07/22 11:28:12 D [0/0] [path video/abc] [rtsp source] s->c RTSP/1.0 200 OK
CSeq: 1
Public: DESCRIBE, SETUP, TEARDOWN, PLAY, PAUSE, OPTIONS
Server: Streaming Server/2.9.0.0

2021/07/22 11:28:12 D [0/0] [path video/abc] [rtsp source] c->s DESCRIBE rtsp://172.16.0.33:3456/Media/Normal?streamindex=1 RTSP/1.0
Accept: application/sdp
CSeq: 2
User-Agent: gortsplib

2021/07/22 11:28:12 D [0/0] [path video/abc] [rtsp source] s->c RTSP/1.0 401 Unauthorized
CSeq: 2
Server: Streaming Server/2.9.0.0
WWW-Authenticate: Digest realm="Streaming Server", nonce="c767de0b94d10848c13d1c87da8b236f"
WWW-Authenticate: NTLM 
WWW-Authenticate: Negotiate 

2021/07/22 11:28:12 D [0/0] [path video/abc] [rtsp source] c->s DESCRIBE rtsp://172.16.0.33:3456/Media/Normal?streamindex=1 RTSP/1.0
Accept: application/sdp
Authorization: Digest username="vivo", realm="Streaming Server", nonce="c767de0b94d10848c13d1c87da8b236f", uri="rtsp://172.16.0.33:3456/Media/Normal?streamindex=1", response="1535b983b505fff6bba4606c1a751b32"
CSeq: 3
User-Agent: gortsplib

2021/07/22 11:28:12 D [0/0] [path video/abc] [rtsp source] s->c RTSP/1.0 200 OK
CSeq: 3
Cache-Control: no-cache
Content-Base: rtsp://172.16.0.33:3456/Media/Normal?streamindex=1/
Content-Length: 481
Content-Type: application/sdp
Date: Thu, 22 Jul 2021 03:28:01 GMT
Expires: Thu, 22 Jul 2021 03:28:01 GMT
Server: Streaming Server/2.9.0.0
X-Accept-Dynamic-Rate: 1
X-Accept-Retransmit: our-retransmit

v=0
o=RTSP 1853326073 627916868 IN IP4 0.0.0.0
s=RTSP server
c=IN IP4 0.0.0.0
t=0 0
a=control:*
a=etag:1234567890
a=range:npt=0-
a=control:*
m=video 0 RTP/AVP 98 96
a=control:trackID=1
b=AS:0
a=rtpmap:98 H265/90000
a=fmtp:98 profile-id=1; sprop-vps=QAEMAf//AWAAAAMAAAMAAAMAAAMAlqwJ; sprop-sps=QgEBAWAAAAMAAAMAAAMAAAMAlqADwIAQ5Za5JMmuWcBSSgAAB9AAAHUwgkA=; sprop-pps=RAHgdrAwxmQ=
m=application 0 RTP/AVP 107
a=control:trackID=3
a=rtpmap:107 vnd.onvif.metadata/90000

2021/07/22 11:28:12 I [0/0] [path video/abc] [rtsp source] ERR: unable to get clock rate of track 0: invalid format ([98 96])

**Comment by aler9** [comment]
Thanks, this has been fixed.
