### ISSUE TITLE
ServerHandlerOnAnnounceContext.Query is always empty

### ISSUE THREAD

**Issue by nu774** [aler9/gortsplib#73]
In ServerSession.handleRequest():
```
pathAndQuery, ok := req.URL.RTSPPath()
if !ok {
	return &base.Response{
		StatusCode: base.StatusBadRequest,
	}, liberrors.ErrServerInvalidPath{}
}

path, query := base.PathSplitQuery(pathAndQuery)
```
In the first line, URL.RTSPPath() returns only path part of the URL, not including query.
In the last line, pathAndQuery doesn't contain query, so query remains always empty.
Is this an intentional behavior?

**Comment by aler9** [comment]
Thanks for reporting this issue, now `ctx.Query` is filled correctly.
