### ISSUE TITLE
Unreleased Resource

### ISSUE THREAD

**Issue by dongjialong2006** [aler9/gortsplib#76]
814: 1667072 [814: 1667072] @ 0xb9012d 0xb900b5 0xba02d5 0xb8d6dc 0x472401
#	0xb9012c	github.com/aler9/gortsplib/pkg/multibuffer.New+0x32c			/app/vendor/github.com/aler9/gortsplib/pkg/multibuffer/multibuffer.go:16
#	0xb900b4	github.com/aler9/gortsplib.(*ServerConn).handleRequestOuter+0x2b4	/app/vendor/github.com/aler9/gortsplib/serverconn.go:512
#	0xba02d4	github.com/aler9/gortsplib.(*ServerConn).run.func3+0x194		/app/vendor/github.com/aler9/gortsplib/serverconn.go:226
#	0xb8d6db	github.com/aler9/gortsplib.(*ServerConn).run+0x3fb			/app/vendor/github.com/aler9/gortsplib/serverconn.go:245

6: 24576 [6: 24576] @ 0xb8dc74 0xb8d3e8 0x472401
#	0xb8dc73	bufio.NewReaderSize+0x993				/usr/local/go/src/bufio/bufio.go:57
#	0xb8d3e7	github.com/aler9/gortsplib.(*ServerConn).run+0x107	/app/vendor/github.com/aler9/gortsplib/serverconn.go:127

**Comment by aler9** [comment]
Sorry but it's impossible to understand what you are trying to communicate. Please open another issue and provide details about the problem (a memory leak?) and how to replicate it.
