### ISSUE TITLE
Bug in SDP Unmarshal

### ISSUE THREAD

**Issue by artofey** [aler9/gortsplib#81]
Hi.
The library does not work with one of my cameras.
The reason is that the track check `func (t *Track) IsH264() bool ` does not work.
It does not work, because the camera gives the SDP lines with a space symbol at the end.
This string: `a=rtpmap:96 H264/90000 `
Therefore, in my case, here the length is 3
```go
vals := strings.Split(v, " ")
if len(vals) != 2 {
	return false
}
```
I'm not sure where exactly to add the fix.
I think I need to add this code before [this line](https://github.com/aler9/gortsplib/blob/main/pkg/sdp/sdp.go#L510)
`line = strings.TrimSpace(line)`
If you agree, I will prepare a pull request

**Comment by aler9** [comment]
Hello, create a PR and it will be merged.
