### ISSUE TITLE
Is it possible to re-export ServerSession.WritePacketRTP() ?

### ISSUE THREAD

**Issue by nu774** [aler9/gortsplib#90]
Could you re-export ServerSession.WritePacketRTP() ?
We could send back RTP packets via ServerSession.WritePacketRTP() to the (special) publishers. This publisher is using a=sendrecv in announce SDP to enable bi-directional streaming.
Now it is impossible, and we cannot use ServerStream.WritePacketRTP for that purpose.

**Comment by aler9** [comment]
Hello, WritePacketRTP() was re-exported, but keep in mind that bidirectional communication is not standardized (RTSP is not WebRTC), the client doesn't support it, and using that function with readers don't work when readers are using multicast.
