### ISSUE TITLE
Invalid SSRC

### ISSUE THREAD

**Issue by marcoLPT** [aler9/gortsplib#95]
rtsp-server very usefull but i've got a problem with a rtsp server ( IbaRtsp) the session ID after the setup got a lazy syntax :
```
SETUP rtsp://121.254.102.104:554/cam2/live RTSP/1.0
CSeq: 3
Transport: RTP/AVP;unicast;client_port=10100-10101;mode=play
User-Agent: gortsplib

RTSP/1.0 200 OK
CSeq: 3
Server: ibaRTSPServer/5.1.4
Session: 121.254.102.120+7789+937239728
Transport: RTP/AVP/UDP;unicast;client_port=10100-10101;server_port=50024-50025;ssrc=937239728

```
thank for your incredible job..

**Comment by aler9** [comment]
Hello, the SSRC is [4 bytes long](https://pkg.go.dev/github.com/pion/rtp#Header) - that server you posted sent a SSRC that is 5 bytes long, therefore it can't be decoded, even if i wanted to. Please contact the authors of that RTSP server and tell them to fix the issue.

**Comment by aler9** [comment]
Maybe they encoded the SSRC as a decimal int; it must be encoded as a hex-encoded byte array.

**Comment by marcoLPT** [comment]
yes i see this yesterday they send SSRC in dec..
